[identities]
hp-laptop = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICCY/7XSfCq7YTu7/z3Dzm1FzVaPbBrCvdOM2opDUm15"
personal-server = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB/jCp7yrN/UtgzaqkHMlyC85j9k0Lp9GUjm15vFJ2zE"

[[paths]]
glob = "hosts/personal-server/secrets/*"
identities = [ "hp-laptop", "personal-server" ]
