ZDOTDIR="$HOME/.config/zsh"
mkdir -p "$ZDOTDIR"

HISTFILE="$ZDOTDIR/history"

autoload -U compinit

zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
compinit -C -d "$zcompdump"
if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
  zcompile "$zcompdump"
fi
 
# Compile zcompdump, if modified, to increase startup speed.
# Execute in the background to not affect the current session
compinit -d "$zcompdump" &!

zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%B%F{blue}Completing %F{yellow}%d%f%b'

eval "$(dircolors -b)"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

setopt autocd

# setopt correct vi
# KEYTIMEOUT=0
